---
browsers_catalog_root: "{{ playbook_dir }}/host_files/localhost/browsers"
browsers_catalog_names:
  - chrome
  - edge
  - brave
  - firefox
  - vivaldi

browsers_state_dir: "{{ user_dir }}/.local/state/macbook-pro/browser-policy"
browsers_chrome_policy_domain: com.google.Chrome
browsers_chrome_policy_stage: "{{ browsers_state_dir }}/com.google.Chrome.plist"
browsers_chrome_policy_dir: "/Library/Managed Preferences/{{ osx_username }}"
browsers_chrome_policy_path: "{{ browsers_chrome_policy_dir }}/com.google.Chrome.plist"
browsers_generated_paths:
  - "{{ browsers_chrome_policy_stage }}"
  - "{{ browsers_chrome_policy_path }}"
